version: '3.8'
name: prefect-infra

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  server:
    image: prefecthq/prefect:2.11.0-python3.11
    restart: unless-stopped
    ports:
     - "4200:4200"
    expose:
      - 4200
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      PREFECT_SERVER_API_HOST: 0.0.0.0
    command: "prefect server start"
    depends_on:
      db:
        condition: service_started

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    restart: unless-stopped
    environment:
      PREFECT_API_URL: ${PREFECT_API_URL}
    depends_on:
      server:
        condition: service_started
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

  alara:
    build:
      context: flows
      dockerfile: ../Docker/alara.Dockerfile
      args:
        - PREFECT_API_URL=${PREFECT_API_URL}
    image: alara.jk:latest
    environment:
      PREFECT_API_URL: ${PREFECT_API_URL}
    command: ["prefect", "deploy", "-n", "alara-test"]
    

volumes:
  postgres-data:
